name: |
  Publish library to NPMJS

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CBNSNDWCH_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-test-publish:
    name: Build, Test, and Publish Library
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}-api

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up NodeJS & NPM
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@cbnsndwch'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn npm publish
